spring.application.name=api-gateway

server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=false

spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=SLENDIT-USER
spring.cloud.gateway.routes[0].uri=lb://SLENDIT-USER
spring.cloud.gateway.routes[0].predicates[0]=Path=/slendit/user/**


spring.cloud.gateway.routes[1].id=SLENDIT-MAIL
spring.cloud.gateway.routes[1].uri=lb://SLENDIT-MAIL
spring.cloud.gateway.routes[1].predicates[0]=Path=/slendit/email/**

